# swees <swisscustodyx.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
]

[DOCUMENTATION]
ORG_NAME="swisscustodyx"
ORG_URL="https://swisscustodyx.github.io/"
ORG_LOGO ="https://swisscustodyx.github.io/img/crown.png"
ORG_OFFICIAL_EMAIL="swisscustody@proton.me"
ORG_SUPPORT_EMAIL="swisscustody@proton.me"
ORG_DESCRIPTION=": POWER BUY SWEESSCUTODY"

[[PRINCIPALS]]
email="swisscustody@proton.me"

[[CURRENCIES]]
code ="QXRP"
name ="QXRP"
issuer = "GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
display_decimals = 1
desc="APY%."
image="https://swisscustodyx.github.io/img/XRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000


[[CURRENCIES]]
code ="SGB"
name ="SWEES GOLD BOND"
issuer = "GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://swisscustodyx.github.io/img/SGB.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code ="BTC"
name ="THIS IS KING"
issuer = "GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://swisscustodyx.github.io/img/BTC.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code ="Kay"
name ="MAKER KAY"
issuer = "GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://swisscustodyx.github.io/img/Kay.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code="CHATGPT"
name="ChatGPT"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="ChatGPT"
image="https://swisscustodyx.github.io/img/chat.png"
status="live"

[[CURRENCIES]]
code ="USD"
name ="UNITED STET BOND"
issuer = "GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://swisscustodyx.github.io/img/USD.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code="GOLD"
name="Gold Bond"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="GolD"
image="https://swisscustodyx.github.io/img/SGB.png"
status="live"



[[CURRENCIES]]
code="RCEO"
name="Received of customers"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Received of customers"
image="https://swisscustodyx.github.io/img/RECO.png"
status="live"


[[CURRENCIES]]
code="BOSS"
name="BOSS"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="BOSS"
image="https://swisscustodyx.github.io/img/BOSS.png"
status="live"


[[CURRENCIES]]
code="BOND"
name="BOND"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="BOND"
image="https://swisscustodyx.github.io/img/BOND.png"
status="live"


[[CURRENCIES]]
code="T"
name="T"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="T"
image="https://swisscustodyx.github.io/img/T.png"
status="live"



[[CURRENCIES]]
code="1oo"
name="100"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="1oo"
image="https://swisscustodyx.github.io/img/100.png"
status="live"


[[CURRENCIES]]
code="Q"
name="Question"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Q"
image="https://swisscustodyx.github.io/img/Q.png"
status="live"



[[CURRENCIES]]
code="Yes"
name="Yes"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Yes"
image="https://swisscustodyx.github.io/img/YES.png"
status="live"

[[CURRENCIES]]
code ="USBS"
name ="UNIT OF USDT"
issuer = "GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://swisscustodyx.github.io/img/USD.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000




[[CURRENCIES]]
code="SNP500"
name="S&P"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="SNP500"
image="https://swisscustodyx.github.io/img/SNP.png"
status="live"


[[CURRENCIES]]
code="DW"
name="📛"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="DW"
image="https://swisscustodyx.github.io/img/DW.png"
status="live"



[[CURRENCIES]]
code="DEX"
name="DX"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="dex"
image="https://swisscustodyx.github.io/img/DEX.png"
status="live"



[[CURRENCIES]]
code="POK"
name="Pakistani Bond"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="POK"
image="https://swisscustodyx.github.io/img/POK.png"
status="live"


[[CURRENCIES]]
code="MBA"
name="MASTAR"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="MASTAR"
image="https://swisscustodyx.github.io/img/MBA.png"
status="live"



[[CURRENCIES]]
code="GDDSX"
name="GDDSX"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="ALL"
image="https://swisscustodyx.github.io/img/STAR.png"
status="live"


[[CURRENCIES]]
code="Wallet"
name="wallet for reword"
issuer="GAPTGYALEEZMQKTYCZGNK6ZGY74Q6SUIDIZIGR5KUE6MZKVGOHWPGTGQ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="wallet"
image="https://swisscustodyx.github.io/img/wallet.png"
status="live"
